### PR TITLE
### MileStone: 1

### PR DESCRIPTION
**Pull request by developerwaleed**
### Requirements for the Project1: 👍 
- Use WebPack ✅ 
- Use GitFlow. ✅ 
- Write plain HTML markup with minimum styling ✅

### CODE REVIEW

**Review by OLIPLICHE — CHANGES_REQUESTED** [review]
Hi @caasperr, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
Linter is green (the last commit have a green check mark (✅)) 👏
README file is descriptive 👏
Commit messages are meaningful 👏 👏
Github flow is correctly used (Pull Request is made from the feature branch into the main branch) 👏

## Required Changes ♻️

- [ ] Please make sure that your project has `basic project structure`: See the example below

a


_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by OLIPLICHE** [comment]
> Hey @OLIPLICHE, Thank you for the suggestion but I want to ask if the thing that you mentioned is a project requirement? as I see that it was not and you are blocking my project to get approved waiting for your reply! Thank you 😊

Hi @caasperr 
Microverse or Code reviewers don't block students' progress. We are here rather help you succeed. `dist` is missing in your structure, which means you missed something in your` webpack` installation etc ...,

**Comment by caasperr** [comment]
hi @OLIPLICHE, I didn't mean to say that but I am using WebPack live. When you run WebPack start it automatically creat the dist folder and automatically deletes it but I can add it and ask for a re-review Thank You. 👍

**Review by rustam-tolipov — APPROVED** [review]
## Hi @caasperr 👋, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
## Congratulations! 🎉 🎉 🎉 🎉 🎉 

Cheers and Happy coding!👏👏👏

Developer-512px-10

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

**Pull request merged**
